### ISSUE TITLE
No mp4 file created

### ISSUE THREAD

**Issue by orksworld** [manishkatyan/bbb-mp4#42]
Hi,

I installed bbb-mp4.  After presentation published no mp4 file created. 

tail -f /var/log/bigbluebutton/post_publish.log
I, [2021-10-28T09:06:57.529659 #24777]  INFO -- : Task: Getting meeting metadata
I, [2021-10-28T09:06:57.531597 #24777]  INFO -- : Recording Ready notify ends
I, [2021-10-28T09:19:53.713002 #29145]  INFO -- : Task: Getting meeting metadata
I, [2021-10-28T09:19:53.998739 #29222]  INFO -- : Recording Ready Notify for [183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1635401937731] starts
I, [2021-10-28T09:19:53.998791 #29222]  INFO -- : Task: Getting meeting metadata
I, [2021-10-28T09:19:54.000528 #29222]  INFO -- : Recording Ready notify ends
I, [2021-10-28T09:45:11.847465 #2154]  INFO -- : MP4 conversion started for 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1635403447546: true
I, [2021-10-28T09:45:12.785176 #2269]  INFO -- : Recording Ready Notify for [183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1635403447546] starts
I, [2021-10-28T09:45:12.785237 #2269]  INFO -- : Task: Getting meeting metadata
I, [2021-10-28T09:45:12.786457 #2269]  INFO -- : Recording Ready notify ends

# ls -l /mnt/scalelite-recordings/var/bigbluebutton/mp4/                                                                                
total 0

**Comment by arun-hel** [comment]
Can you try to convert manually?
go to the bbb-mp4 location and run `bash bbb-mp4.sh <meetinr_id>`

**Comment by orksworld** [comment]
Hi,

 

I am sending the output.

/var/www/bbb-mp4# ./bbb-mp4.sh 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1635415298846

b661cb13b494e7f626dec3811c1d3589415e4f5019396ddd37f0ae040d7cd7b3

 

Still no mp4 file created.

**Comment by arun-hel** [comment]
Have you run the below commands during installation?
```sh
# give bigbluebutton user sudo access
usermod -aG sudo bigbluebutton

# make sudo access passwordless
sudo visudo
# add the following line at the end of the file
bigbluebutton ALL=(ALL) NOPASSWD: ALL
```

**Comment by arun-hel** [comment]
By default mp4 will be saved  at /var/www/bigbluebutton-default/recording
If you want to change the mp4 saving location please change  COPY_TO_LOCATION in .env

**Comment by orksworld** [comment]
Hi, 

 

I have edited the .env file.

 

# more /var/www/bbb-mp4/.env

BBB_DOMAIN_NAME=aaa.aaa.com

COPY_TO_LOCATION=/mnt/scalelite-recordings/var/bigbluebutton/mp4

**Comment by orksworld** [comment]
Hi,

 

I runned the commands already,

 

 

# This file MUST be edited with the 'visudo' command as root.

#

# Please consider adding local content in /etc/sudoers.d/ instead of

# directly modifying this file.

#

# See the man page for details on how to write a sudoers file.

#

Defaults        env_reset

Defaults        mail_badpass

Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

 

# Host alias specification

 

# User alias specification

 

# Cmnd alias specification

 

# User privilege specification

root    ALL=(ALL:ALL) ALL

 

# Members of the admin group may gain root privileges

%admin ALL=(ALL) ALL

 

# Allow members of group sudo to execute any command

%sudo   ALL=(ALL:ALL) ALL

 

# See sudoers(5) for more information on "#include" directives:

 

#includedir /etc/sudoers.d

bigbluebutton ALL=(ALL) NOPASSWD: ALL

**Comment by mikesrus** [comment]
same too. mp4 file not creating. :(

**Comment by arun-hel** [comment]
What is the bbb version? 
If possible can you provide mp4 container logs?

How to get the logs:
- start mp4 conversion manually : go to bbb-mp4 installation location, and run `bash bbb-mp4.sh <meeting_id>`
- get the logs `docker logs <meeting_id> -f`

**Comment by mikesrus** [comment]
BigBlueButton Server 2.3.15 (2482)

`root@bbb:/var/www/bbb-mp4# bash bbb-mp4.sh 32255eb1c4360cee103ebcebeed03e094d442b58-1635870581223e5956ec61f23e92440fe93d87dcbe75213f422400139bc4970c93beb07368c80`

docker logs <meeting_id> -f

```
root@bbb:/var/www/bbb-mdocker logs 32255eb1c4360cee103ebcebeed03e094d442b58-1635870581223 -f1223
Starting pulseaudio...
Waiting for pulseaudio to start...
PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)
Recording found
Error: Evaluation failed: TypeError: Cannot read property 'duration' of null
    at __puppeteer_evaluation_script__:2:68
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async main (/usr/src/app/bbb-mp4.js:83:29)
```

**Comment by mikesrus** [comment]
sorry. my it was a DNS setup error. file created and all works

**Comment by orksworld** [comment]
Hi,

 

BigBlueButton Server 2.3.15 (2482)

                    Kernel version: 4.15.0-158-generic

                      Distribution: Ubuntu 18.04.6 LTS (64-bit)

**Comment by arun-hel** [comment]
@orksworld 

>  If possible can you provide mp4 container logs?
> 
> How to get the logs:
> 
> * start mp4 conversion manually : go to bbb-mp4 installation location, and run `bash bbb-mp4.sh <meeting_id>`
> * get the logs `docker logs <meeting_id> -f`

**Comment by orksworld** [comment]
Hi,

 

In the logs i found out that it was a permission error. Thanks for your help.

**Comment by orksworld** [comment]
The created file owner is root. Is there a way of creating with bigbluebutton user. We want to use this with our scalelite server. I think file permissions should be bigbluebutton for scalelit Access it.

**Comment by arun-hel** [comment]
@orksworld  There are many ways to achieve this.
One of the way could be changing COPY_TO_LOCATION to some other folder and use inotify to observe the changes in COPY_TO_LOCATION and then change the ownership of mp4  and transfer it to wherever you prefer.

**Comment by arun-hel** [comment]
Closing due to inactivity.

**Comment by femz12** [comment]
@arun-hel 

I got this in log

```
I, [2024-05-14T07:41:46.702302 #47696]  INFO -- : MP4 conversion started for <meetinr_id>: true
I, [2024-05-14T07:41:47.103113 #47710]  INFO -- : Recording Ready Notify for [<meetinr_id>] starts
I, [2024-05-14T07:41:47.103173 #47710]  INFO -- : Task: Getting meeting metadata
I, [2024-05-14T07:41:47.103819 #47710]  INFO -- : Recording Ready notify ends
```

but when I check the recording folder; there was no file

but when I did

`bash bbb-mp4.sh <meetinr_id>`  the file got created, please what could be the problem?

I have gone through the installation over and over again.

I have added all the neccessary permissions.
