### ISSUE TITLE
Supports BBB 2.4?

### ISSUE THREAD

**Issue by Shaalam3** [manishkatyan/bbb-mp4#43]
Hi, I am already using bbb-mp4 in version 2.3 and everything works fine. Now on installing in new BBB 2.4, it seems that the mp4 process is not auto started. On running the mp4 process manually, it works fine and mp4 video is created. But it is not starting automatically in version 2.4. My doubt is, is bbb-mp4 supports BBB version 2.4 OR Am I missing something? Kindly help.

**Comment by arun-hel** [comment]
@Shaalam3  If you are upgrading from BBB 2.3 to 2.4 BBB-mp4 should work. Can you see any error in  post_publish logs?. However, if it is a fresh bbb 2.4 installation then you may face this issue because in older bbb they were using trollop gem, But in 2.4 they are using optimist gem in post_publish scripts. We are working on a fix.

**Comment by Shaalam3** [comment]
> @Shaalam3 If you are upgrading from BBB 2.3 to 2.4 BBB-mp4 should work. Can you see any error in post_publish logs?. However, if it is a fresh bbb 2.4 installation then you may face this issue because in older bbb they were using trollop gem, But in 2.4 they are using optimist gem in post_publish scripts. We are working on a fix.

Hi, Thanks for the reply. 
I tired with new installation of BBB 2.4 only. I have not yet tried with upgrading from 2.3 to 2.4. Waiting for the fix, thanks for that.

**Comment by arun-hel** [comment]
Here is the workaround

open `/usr/local/bigbluebutton/core/scripts/post_publish/bbb_mp4.rb`
`nano /usr/local/bigbluebutton/core/scripts/post_publish/bbb_mp4.rb`

At line number  3 change `require "trollop"` to `require "optimist"` 
At line number 10 change `opts = Trollop::options do` to  `opts = Optimist::options do`

Then restart bbb `bbb-conf --restart`

Let know if this fixes your issue.

**Comment by amg-web** [comment]
it should fix. I did not check
that's becaouse gem trollop is not installed on fresh installed bbb 2.4 servers
but it should be Ok if you upgraded from v.2.3

I have another problem 
I try to build my own imge and get infobar **chrome is being controlled by automated software**

what is the reason of this? 
  manishkatyan/bbb-mp4 uses crome-browser version 91 which should show it too, but it does not.
May be I miss something?

**Comment by arun-hel** [comment]
@amg-web  Have you made any changes to bbb-mp4.js?

**Comment by amg-web** [comment]
No
After I replaced google chrome with chromium problem solved

**Comment by amg-web** [comment]
@arun-hel

Hi,

I am working to move this to alpine based image.
Any help will be appriciated.
I'm not familiar with Puppeteer

current in use chromium 98 with Puppeteer 13.1

I have a few errors:
`Error: Failed to launch the browser process!
[0219/130529.747412:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747492:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747515:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747559:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747633:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747673:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747710:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747728:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747757:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)
[0219/130529.747830:WARNING:process_reader_linux.cc(76)] sched_getscheduler: Function not implemented (38)


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at Interface.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:219:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
/usr/src/app/mp4.js:123
        await page.close()
                   ^

TypeError: Cannot read properties of undefined (reading 'close')
    at main (/usr/src/app/mp4.js:123:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by Atefe97** [comment]
> Here is the workaround
> 
> open `/usr/local/bigbluebutton/core/scripts/post_publish/bbb_mp4.rb` `nano /usr/local/bigbluebutton/core/scripts/post_publish/bbb_mp4.rb`
> 
> At line number 3 change `require "trollop"` to `require "optimist"` At line number 10 change `opts = Trollop::options do` to `opts = Optimist::options do`
> 
> Then restart bbb `bbb-conf --restart`
> 
> Let know if this fixes your issue.

i tried it with fresh new installation and it works perfectly.
thanks @arun-hel
