### ISSUE TITLE
 Possible bug?

### ISSUE THREAD

**Issue by mricim** [manishkatyan/bbb-mp4#64]
Sometimes I run into this problem:

```
Starting pulseaudio...
Waiting for pulseaudio to start...
(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
    at main (/usr/src/app/bbb-mp4.js:122:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r869685 is guaranteed to work.
    at Timeout.onTimeout (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:205:20)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by arun-hel** [comment]
@mricim Is bigbluebutton playback recording available?  can it be played ?

**Comment by mricim** [comment]
@arun-hel  Yeah.  Many times it keeps processing and everything is fine, the other times I run again and it works fine.
