### ISSUE TITLE
Records With Large Size didn't convert to MP4 on BBB 2.6

### ISSUE THREAD

**Issue by SepehrTorahi** [manishkatyan/bbb-mp4#66]
I have problem with records that have large size 
They don't convert to mp4 , but at the same time other records convert very well and i can download them.
Also when i used  bbb-mp4.sh to convert them manually i had the same problem, it's not successful.
I tried to rebuild them but it's not helpful.
I Need Help :)

**Comment by arun-hel** [comment]
@SepehrTorahi  What is the duration of the recordings?

**Comment by parpsy** [comment]
I try to convert a recording of around 2hours , and i get the following error : 
```
Starting pulseaudio...
Waiting for pulseaudio to start...
Recording found
Error: Evaluation failed: TypeError: Cannot read property 'duration' of null
    at __puppeteer_evaluation_script__:2:68
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async main (/usr/src/app/bbb-mp4.js:82:29)
   ```
  I wanna also ask if a video length is for example 1 hour, does it take 1 hour for ffmepg to convert it to mp4 ? as it should open it in chrome and record it.
  Thank you !

**Comment by Javohle** [comment]
I got an solution, i think, for big files, with big record i detected that time to get all the thing load and see timeline in the bottom (like 4:15:21 for examle) for video length is big too 
And the second thing is that docker container bbb-mp4 called to convert failed with error t (time) is not defined 
so i just made      line 

   // Check if recording exists (search "404" message)
        await page.waitForTimeout(**5** * 1000)

in _bbb-mp4.js_ to be like this:  

        // Check if recording exists (search "404" message)
        await page.waitForTimeout(30 * 1000)

Then i rebuild docker 
and it starts to work!

**Comment by Javohle** [comment]
In workflow process it gives in log some other 404 errors but thay are connected to resources which may but hadn't been used in meeting (like notes etc.) but if there are no ffmpeg errors after process start it is working till the end. 
And yes the convertation tooks the same time as the record lasts , like you were sitting and recording it from screen but without sitting and recording)

**Comment by Nick64M** [comment]
I'm testing on BBB 3.016. It records. I haven't tested long-term yet.
